# Generated by Django 4.2.4 on 2023-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_owner_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user.png', null=True, upload_to='profiles/'),
        ),
    ]
