# Generated by Django 4.2.4 on 2023-08-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_tag_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='project.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 22, 18, 39, 55, 208591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 8, 22, 18, 40, 23, 327697, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
